<?xml version="1.0" encoding="utf-8"?><Database Name="Peter" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MORTEN-PC\SQLEXPRESS;Initial Catalog=Peter;Integrated Security=True" SettingsObjectName="Peter.Properties.Settings" SettingsPropertyName="PeterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" />
      <Column Name="html" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" />
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>