<?xml version="1.0" encoding="utf-8"?><Database Name="Peter" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ESJ-VISION\SQLEXPRESS;Initial Catalog=Peter;Integrated Security=True" SettingsObjectName="PetersWeb.Properties.Settings" SettingsPropertyName="PeterConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="html" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Page_TermToPage" Member="TermToPages" ThisKey="id" OtherKey="pageID" Type="TermToPage" />
      <Association Name="Page_Shingle" Member="Shingles" ThisKey="id" OtherKey="url" Type="Shingle" />
    </Type>
  </Table>
  <Table Name="dbo.TermToPage" Member="TermToPages">
    <Type Name="TermToPage">
      <Column Name="termID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Page_TermToPage" Member="Page" ThisKey="pageID" OtherKey="id" Type="Page" IsForeignKey="true" />
      <Association Name="Term_TermToPage" Member="Term" ThisKey="termID" OtherKey="id" Type="Term" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shingles" Member="Shingles">
    <Type Name="Shingle">
      <Column Name="url" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="shingle" Member="shingle1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Page_Shingle" Member="Page" ThisKey="url" OtherKey="id" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Terms" Member="Terms">
    <Type Name="Term">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="term" Member="term1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Term_TermToPage" Member="TermToPages" ThisKey="id" OtherKey="termID" Type="TermToPage" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteAllPages" Method="DeleteAllPages">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertToken" Method="insertToken">
    <Parameter Name="term" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="url" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>